service: store

image: amitgiri2062/store

servers:
  web:
    - 192.168.100.1

proxy:
  ssl: true
  host: app.example.com

registry:
  username: amitgiri2062
  password:
     - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
    - DATABASE_URL   # required for PostgreSQL

  clear:
    SOLID_QUEUE_IN_PUMA: true

# REMOVE old SQLite volume (unused with PostgreSQL)
# volumes:
#   - "store_storage:/rails/storage"

# Add PostgreSQL as accessory service
accessories:
  postgres:
    image: postgres:15
    host: 192.168.100.1          # Same machine OR change if needed
    port: "127.0.0.1:5432:5432"   # Exposes internally & to host
    env:
      clear:
        POSTGRES_DB: store_production
        POSTGRES_USER: store
      secret:
        - POSTGRES_PASSWORD       # stored in .kamal/secrets
    directories:
      - data:/var/lib/postgresql/data

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole --include-password"

asset_path: /rails/public/assets

builder:
  arch: amd64
